import Link from "next/link";
import { getAdminConsultationLeads, type LeadFilters } from "@/server/admin/consultation-leads";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;
const one = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
const fmt = (v: string) => new Date(v).toLocaleDateString("ru-RU");
function href(filters: LeadFilters, page?: number) { const p = new URLSearchParams(); Object.entries({ ...filters, page: page?.toString() }).forEach(([k,v]) => { if (v) p.set(k, v); }); return `/ru/admin/leads${p.toString() ? `?${p}` : ""}`; }

export default async function AdminLeadsPage({ searchParams }: { searchParams: SearchParams }) {
  const raw = await searchParams; const filters = Object.fromEntries(Object.entries(raw).map(([k,v]) => [k, one(v)])) as LeadFilters; const result = await getAdminConsultationLeads(filters); const listUrl = href(filters);
  return <main className="min-h-[70vh] bg-slate-50 py-10 sm:py-14"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Link href="/ru/admin" className="text-sm underline">Администрирование</Link><h1 className="mt-3 text-3xl font-semibold">Заявки на консультацию</h1><p className="mt-2 text-sm text-slate-500">Только просмотр заявок и состояний уведомлений.</p>
    <form method="get" className="my-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-5"><label className="text-sm">Поиск<input name="q" defaultValue={filters.q} maxLength={100} placeholder="Имя, email или компания" className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm">Статус<select name="status" defaultValue={filters.status ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Все</option>{["new","contacted","consultation_scheduled","closed"].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm">Дата заявки с<input type="date" name="from" defaultValue={filters.from} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm">Дата заявки по<input type="date" name="to" defaultValue={filters.to} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm">Уведомление<select name="delivery" defaultValue={filters.delivery ?? ""} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Все</option>{["queued","sending","sent","failed"].map(s=><option key={s}>{s}</option>)}</select></label><div className="flex items-end gap-3"><button className="rounded-lg bg-blue-800 px-4 py-2 font-semibold text-white">Применить</button><Link href="/ru/admin/leads" className="rounded-lg border px-4 py-2">Сбросить фильтры</Link></div></form>
    {!result.rows.length ? <div className="rounded-2xl border bg-white p-8 text-slate-600">Заявки не найдены.</div> : <><div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[1100px] w-full text-left"><thead className="bg-slate-100 text-sm"><tr>{["Дата заявки","Контакт","Компания","Диагностика","Статус","Уведомление","Действие"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody>{result.rows.map(r=><tr key={r.id} className="border-t align-top"><td className="px-3 py-4">{fmt(r.createdAt)}</td><td className="px-3 py-4"><p className="font-medium">{r.name}</p><p className="text-sm text-slate-500">{r.email}</p>{r.hasComment && <p className="text-xs text-slate-500">Есть комментарий</p>}</td><td className="px-3 py-4">{r.companyName}</td><td className="px-3 py-4 text-sm">{r.diagnosticId.slice(0,8)}…</td><td className="px-3 py-4">{r.status}</td><td className="px-3 py-4 text-sm">{r.deliveryStatus ?? "—"}{r.jobStatus ? ` / ${r.jobStatus}` : ""}</td><td className="px-3 py-4"><Link className="font-semibold text-blue-800 underline" href={`/ru/admin/leads/${r.id}?returnTo=${encodeURIComponent(listUrl)}`}>Открыть</Link></td></tr>)}</tbody></table></div><div className="mt-5 flex justify-between text-sm"><span>Страница {result.page} из {result.totalPages} · всего {result.total}</span><span className="flex gap-3">{result.page>1&&<Link className="rounded border px-3 py-2" href={href(filters,result.page-1)}>Назад</Link>}{result.page<result.totalPages&&<Link className="rounded border px-3 py-2" href={href(filters,result.page+1)}>Далее</Link>}</span></div></>}
  </div></main>;
}
