import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/server/auth/admin";
import { getAdminDiagnosticDetail } from "@/server/admin/diagnostic-detail";
import { safeAdminReturnTo } from "@/server/admin/return-to";

const format = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value).replace(".", ",");
const profileValue = (value: unknown) => value === null || value === undefined || value === "" ? "Не указано" : String(value);
const date = (value: string | null) => value ? new Date(value).toLocaleDateString("ru-RU") : "—";
const reportSections = [["Краткое резюме", "summary"], ["Главный управленческий диагноз", "main_diagnosis"], ["Что означает текущий индекс управляемости", "manageability_index_text"], ["Сильные стороны системы управления", "strengths"], ["Ключевые проблемные зоны", "key_problem_zones"], ["Главное ограничение роста", "growth_constraint"], ["Риски, если ничего не менять", "implementation_risks"], ["Первые действия руководителя", "first_actions"], ["План на 30 дней", "plan_30_days"], ["План на 60 дней", "plan_60_days"], ["План на 90 дней", "plan_90_days"], ["Следующий рекомендуемый шаг", "next_step"]] as const;

export default async function AdminDiagnosticDetailPage({ params, searchParams }: { params: Promise<{ diagnosticId: string }>; searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin();
  const { diagnosticId } = await params;
  const query = searchParams ? await searchParams : {};
  const returnTo = safeAdminReturnTo(Array.isArray(query.returnTo) ? query.returnTo[0] : query.returnTo, "/ru/admin/diagnostics");
  const data = await getAdminDiagnosticDetail(diagnosticId);
  if (!data) notFound();
  const resultMap = new Map(data.blockResults.map((row) => [row.block_id, row]));
  return <main className="min-h-[70vh] bg-slate-50 py-10 sm:py-14"><div className="mx-auto max-w-6xl space-y-6 px-5 sm:px-8">
    <div>{query.returnTo ? <Link href={returnTo} className="text-sm underline">← Назад к заявке</Link> : <Link href="/ru/admin/diagnostics" className="text-sm underline">← К списку диагностик</Link>}<h1 className="mt-3 text-3xl font-semibold text-slate-950">Диагностика</h1></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Сведения о диагностике</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-slate-500">Компания</dt><dd>{profileValue(data.company?.name)}</dd></div><div><dt className="text-slate-500">Пользователь</dt><dd>{profileValue(data.user?.full_name)}</dd></div><div><dt className="text-slate-500">Статус</dt><dd>{data.diagnostic.status}</dd></div><div><dt className="text-slate-500">Дата начала</dt><dd>{date(data.diagnostic.started_at)}</dd></div><div><dt className="text-slate-500">Завершена</dt><dd>{date(data.diagnostic.completed_at)}</dd></div><div><dt className="text-slate-500">Индекс управляемости</dt><dd>{format(data.result?.display_manageability_index)}</dd></div><div><dt className="text-slate-500">Уровень зрелости</dt><dd>{profileValue(data.result?.maturity_label)}</dd></div><div><dt className="text-slate-500">ID диагностики</dt><dd className="break-all text-xs">{data.diagnostic.id}</dd></div></dl></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Профиль компании</h2>{data.profileUnavailable ? <p className="mt-3 text-sm text-slate-600">Исторический профиль компании недоступен.</p> : null}<dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Название компании</dt><dd>{profileValue(data.company?.name)}</dd></div><div><dt className="text-slate-500">Страна</dt><dd>{profileValue(data.company?.country)}</dd></div><div><dt className="text-slate-500">Отрасль</dt><dd>{profileValue(data.company?.industry_label)}</dd></div><div><dt className="text-slate-500">Продукты</dt><dd className="whitespace-pre-wrap">{profileValue(data.company?.products)}</dd></div><div><dt className="text-slate-500">Клиенты / клиентские сегменты</dt><dd className="whitespace-pre-wrap">{profileValue(data.company?.customer_segments)}</dd></div><div><dt className="text-slate-500">Каналы продаж</dt><dd className="whitespace-pre-wrap">{profileValue(data.company?.sales_channels)}</dd></div><div><dt className="text-slate-500">Число сотрудников</dt><dd>{profileValue(data.company?.employee_count)}</dd></div><div><dt className="text-slate-500">Годовой оборот</dt><dd>{profileValue(data.company?.annual_revenue_label)}</dd></div><div><dt className="text-slate-500">Возраст компании</dt><dd>{profileValue(data.company?.company_age_years)}</dd></div><div><dt className="text-slate-500">Количество уровней управления</dt><dd>{profileValue(data.company?.management_levels)}</dd></div><div><dt className="text-slate-500">Ключевые проблемы компании</dt><dd className="whitespace-pre-wrap">{profileValue(data.company?.key_problems)}</dd></div><div><dt className="text-slate-500">Главные цели компании</dt><dd className="whitespace-pre-wrap">{profileValue(data.company?.main_goals)}</dd></div></dl></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Результаты диагностики</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.blocks.map((block) => { const score = resultMap.get(block.id); return <div key={block.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium">{block.title}</p><p className="mt-1 text-sm text-slate-600">{score ? `${format(score.display_score)} (raw: ${format(score.raw_score)})` : "Результат отсутствует"}</p></div>; })}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Ответы</h2><div className="mt-4 space-y-5">{data.blocks.map((block) => <details key={block.id} open className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-medium">{block.title}</summary><div className="mt-4 space-y-4">{block.questions.map((question) => <div key={question.questionId} className="border-t border-slate-100 pt-3"><p className="text-sm font-medium">{question.position}. {question.prompt}</p><p className="mt-1 text-sm text-slate-600">Ответ: {question.answer?.text_value ?? (question.answer?.numeric_value === null || question.answer?.numeric_value === undefined ? "—" : question.answer.numeric_value)}</p></div>)}</div></details>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">AI-отчёты</h2><div className="mt-4 space-y-4">{data.reports.length ? data.reports.map((report) => <article key={report.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium">Версия {report.version} · {report.status}</p><p className="mt-1 text-sm text-slate-600">Модель: {report.model} · Prompt: {report.prompt_version} · Schema: {report.schema_version} · {date(report.created_at)}</p>{report.status === "completed" && report.structured_content && <div className="mt-4 space-y-3">{reportSections.map(([title, key], index) => { const value = (report.structured_content as Record<string, unknown>)[key]; return <div key={key}><h3 className="font-medium">{index + 1}. {title}</h3>{Array.isArray(value) ? <ul className="list-disc pl-5 text-sm text-slate-700">{value.map((item, i) => <li key={i}>{String(item)}</li>)}</ul> : <p className="whitespace-pre-wrap text-sm text-slate-700">{String(value ?? "—")}</p>}</div>; })}</div>}</article>) : <p className="text-slate-600">AI-отчёты отсутствуют.</p>}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">PDF-артефакты</h2><div className="mt-4 space-y-3">{data.artifacts.length ? data.artifacts.map((artifact) => <div key={artifact.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><span>Отчёт v{artifact.ai_report_version} · {artifact.template_version} · {artifact.status}</span>{artifact.status === "ready" && <a className="rounded-lg border border-slate-300 px-3 py-2 text-sm" href={`/api/admin/report-artifacts/${artifact.id}`}>Открыть PDF</a>}</div>) : <p className="text-slate-600">PDF не сформирован.</p>}</div></section>
  </div></main>;
}
