#!/usr/bin/env python3
"""Generate a deterministic Supabase SQL seed from the approved methodology CSV."""
import csv, hashlib, uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "METHODOLOGY_RU_1_0.csv"
out = ROOT / "supabase/migrations/20260911000200_methodology_ru_1_0_seed.sql"
rows = list(csv.DictReader(source.open(encoding="utf-8-sig", newline="")))
if len(rows) != 84 or len({r["question_key"] for r in rows}) != 84:
    raise SystemExit("Methodology CSV must contain 84 unique questions")
if len({r["block_code"] for r in rows}) != 10:
    raise SystemExit("Methodology CSV must contain 10 blocks")

def q(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"

def uid(kind: str, key: str) -> str:
    return str(uuid.uuid5(uuid.UUID("7cb6b3ce-09ea-4cb7-8b3b-6a3c715a0f4e"), f"RU-1.0:{kind}:{key}"))

def rows_sql(table, columns, values):
    return f"insert into public.{table} ({', '.join(columns)}) values\n" + ",\n".join("  (" + ", ".join(values(row) if callable(values) else values for _ in [0]) + ")" for row in [])

content_hash = hashlib.sha256(source.read_bytes()).hexdigest()
definition_id = uid("definition", "manageability")
version_id = uid("version", "RU-1.0")
blocks = []
for r in rows:
    if r["block_code"] not in [b["key"] for b in blocks]:
        blocks.append({"key": r["block_code"], "position": r["block_order"], "title": r["block_title"], "weight": r["block_weight"], "id": uid("block", r["block_code"])})

sql = ["-- Generated by scripts/generate_methodology_seed.py from METHODOLOGY_RU_1_0.csv.", "begin;", f"insert into public.diagnostic_definitions (id,key) values ({q(definition_id)},'manageability') on conflict (key) do nothing;", f"insert into public.diagnostic_versions (id,definition_id,version_number,status,content_hash,source_file,published_at) values ({q(version_id)},{q(definition_id)},1,'published',{q(content_hash)},'METHODOLOGY_RU_1_0.csv',now()) on conflict (definition_id,version_number) do nothing;", f"insert into public.diagnostic_version_translations (version_id,locale,title,description) values ({q(version_id)},'ru','Диагностика управляемости компании','Методика RU-1.0') on conflict do nothing;"]
for b in blocks:
    sql.append(f"insert into public.diagnostic_blocks (id,version_id,key,position,weight,is_active) values ({q(b['id'])},{q(version_id)},{q(b['key'])},{b['position']},{b['weight']},true) on conflict (version_id,key) do nothing;")
    sql.append(f"insert into public.diagnostic_block_translations (block_id,locale,title) values ({q(b['id'])},'ru',{q(b['title'])}) on conflict do nothing;")
for r in rows:
    question_id = uid("question", r["question_key"])
    block_id = uid("block", r["block_code"])
    sql.append("insert into public.questions (id,version_id,block_id,key,position,answer_type,weight,is_required,is_active,reverse_score,legacy_ai_context_label,legacy_bubble_unique_id) values (" + ",".join([q(question_id),q(version_id),q(block_id),q(r["question_key"]),r["question_order"],q(r["question_type"]),r["question_weight"],r["is_required"],r["is_active"],r["reverse_score"],q(r["legacy_ai_context_label"]),q(r["legacy_bubble_unique_id"])]) + ") on conflict (version_id,key) do nothing;")
    sql.append(f"insert into public.question_translations (question_id,locale,prompt,help_text) values ({q(question_id)},'ru',{q(r['question_text'])},{q(r['help_text']) if r['help_text'] else 'null'}) on conflict do nothing;")
    if r["question_type"] == "scale_0_4":
        for score in range(5):
            option_id = uid("option", f"{r['question_key']}:{score}")
            sql.append(f"insert into public.question_options (id,question_id,key,position,score_value) values ({q(option_id)},{q(question_id)},{q(f'score_{score}')},{score+1},{score}) on conflict (question_id,key) do nothing;")
            sql.append(f"insert into public.question_option_translations (option_id,locale,label) values ({q(option_id)},'ru',{q(str(score+1))}) on conflict do nothing;")
sql.append(f"insert into public.scoring_policies (version_id,engine_key,engine_version,schema_version,configuration,policy_hash) values ({q(version_id)},'pending_stage_5','1','1','{{}}'::jsonb,{q(content_hash)}) on conflict (version_id) do nothing;")
sql += ["commit;", ""]
out.write_text("\n".join(sql), encoding="utf-8")
print(f"Generated {out} from {source}: {len(rows)} questions, {len(blocks)} blocks")
