-- Stage 12.1: publish a new methodology version without mutating RU-1.0.
begin;
do $$
declare
  v_definition uuid;
  v_old_version uuid := '656e05fd-66c4-50bf-908f-53565525dd5a';
  v_version uuid := 'c5d7b1d0-1f4f-4e93-8af6-12b7d0e2f201';
begin
  select id into v_definition from public.diagnostic_definitions where key = 'manageability';
  if v_definition is null then raise exception 'manageability definition missing'; end if;
  insert into public.diagnostic_versions (id,definition_id,version_number,status,content_hash,source_file,published_at)
  values (v_version,v_definition,2,'published','stage12-1-mvp-question-bank-v2','METHODOLOGY_RU_2_0.csv',now())
  on conflict (definition_id,version_number) do nothing;
  insert into public.diagnostic_version_translations (version_id,locale,title,description)
  values (v_version,'ru','Диагностика управляемости компании','Методика RU-2.0') on conflict do nothing;
  create temporary table _stage12_blocks(old_id uuid primary key,new_id uuid not null,key text not null,position integer not null) on commit drop;
  insert into _stage12_blocks select id,gen_random_uuid(),key,position from public.diagnostic_blocks where version_id=v_old_version;
  insert into public.diagnostic_blocks (id,version_id,key,position,weight,is_active)
  select m.new_id,v_version,b.key,b.position,b.weight,b.is_active from _stage12_blocks m join public.diagnostic_blocks b on b.id=m.old_id;
  insert into public.diagnostic_block_translations (block_id,locale,title,description)
  select m.new_id,t.locale,case b.key when 'strategy' then 'Стратегия' when 'structure' then 'Организационная структура' when 'processes' then 'Процессы и операционная эффективность' when 'goals_kpi' then 'Цели и показатели' when 'management_rhythm' then 'Управленческий ритм' when 'team' then 'Зрелость команды' when 'motivation' then 'Инновации и развитие' when 'culture' then 'Корпоративная культура' else t.title end,t.description
  from _stage12_blocks m join public.diagnostic_blocks b on b.id=m.old_id join public.diagnostic_block_translations t on t.block_id=m.old_id;
  create temporary table _stage12_questions(old_id uuid primary key,new_id uuid not null,key text not null) on commit drop;
  insert into _stage12_questions select q.id,gen_random_uuid(),q.key from public.questions q where q.version_id=v_old_version;
  insert into public.questions (id,version_id,block_id,key,position,answer_type,weight,is_required,is_active,reverse_score,legacy_ai_context_label,legacy_bubble_unique_id)
  select m.new_id,v_version,b.new_id,q.key,q.position,q.answer_type,q.weight,q.is_required,q.is_active,q.reverse_score,q.legacy_ai_context_label,q.legacy_bubble_unique_id from _stage12_questions m join public.questions q on q.id=m.old_id join _stage12_blocks b on b.old_id=q.block_id;
  insert into public.question_translations (question_id,locale,prompt,help_text)
  select q2.new_id,t.locale,t.prompt,t.help_text from _stage12_questions q2 join public.question_translations t on t.question_id=q2.old_id;
  update public.question_translations t set prompt='Какую главную управленческую проблему Вы хотите решить в ближайшие 3–6 месяцев? Опишите ее причины и объясните, почему Вы ставите ей высший приоритет (Ваши развернутые ответы позволят сделать отчет более содержательным).' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='main_management_problem' and t.locale='ru';
  update public.question_translations t set prompt='У компании есть ясная стратегия: мы можем кратко объяснить, где и за счёт чего собираемся выигрывать, а также от каких направлений и возможностей сознательно отказываемся.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_clarity' and t.locale='ru';
  update public.question_translations t set prompt='Мы чётко понимаем, какую ценность создаём для целевых клиентов, какую их проблему решаем и почему они выбирают нас среди альтернатив.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_alignment' and t.locale='ru';
  update public.question_translations t set prompt='Мы осознанно определили приоритетные рынки, клиентские сегменты, продукты и каналы, на которых концентрируем ресурсы, а также направления, которые не считаем приоритетными.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_resources_focused' and t.locale='ru';
  update public.question_translations t set prompt='У компании есть 3–5 ключевых стратегических целей на ближайшие 2–3 года, и для каждой определены измеримые результаты, по которым можно объективно оценить её достижение.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_market_search' and t.locale='ru';
  update public.question_translations t set prompt='Мы регулярно анализируем ключевые внешние изменения, предположения и риски стратегии, рассматриваем возможные сценарии развития и понимаем, при каких условиях стратегию потребуется пересмотреть.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_competitive_advantages' and t.locale='ru';
  update public.question_translations t set prompt='Мы понимаем, какие компетенции, ресурсы, активы и особенности бизнес-модели создают наши устойчивые конкурентные преимущества, и целенаправленно их усиливаем.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_decision_making_priorities' and t.locale='ru';
  update public.question_translations t set prompt='Основные проекты и инициативы компании непосредственно связаны со стратегическими целями; инициативы, не создающие стратегической ценности, не получают приоритетных ресурсов.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_resources_priority' and t.locale='ru';
  update public.question_translations t set prompt='Мы понимаем, какие люди, компетенции, финансовые и другие ресурсы необходимы для реализации стратегии, видим существующие дефициты и распределяем ресурсы в соответствии со стратегическими приоритетами.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_responsability' and t.locale='ru';
  update public.question_translations t set prompt='В компании определён понятный порядок принятия стратегических решений: известно, кто готовит варианты, кто участвует в обсуждении и кто принимает окончательное решение.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_check_prerequisites' and t.locale='ru';
  update public.question_translations t set prompt='Реализация стратегии регулярно оценивается по фактическим результатам, а сама стратегия и стратегические инициативы корректируются, когда меняются результаты, исходные предположения или внешняя среда.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='strategy_regularly_review' and t.locale='ru';
  update public.question_translations t set prompt='Организационная структура соответствует текущей стратегии, бизнес-модели и масштабу компании и своевременно изменяется вместе с развитием бизнеса.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='role_clarity' and t.locale='ru';
  update public.question_translations t set prompt='Для каждого значимого результата и ключевой функции определён персональный владелец, который обладает необходимыми полномочиями и несёт ответственность за результат.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='understands_area_responsibility' and t.locale='ru';
  update public.question_translations t set prompt='В распределении функций и ответственности между подразделениями нет существенных дублирований и «белых пятен», за которые фактически никто не отвечает.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='balance_authority_responsibility' and t.locale='ru';
  update public.question_translations t set prompt='Количество уровней управления и число прямых подчинённых у руководителей позволяют им качественно выполнять управленческую работу и не создают системной перегрузки.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='decision_making_procedure' and t.locale='ru';
  update public.question_translations t set prompt='Роли собственника, генерального директора и топ-команды чётко разделены; стратегическое руководство не подменяет собой операционное управление.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='no_duplication_functions' and t.locale='ru';
  update public.question_translations t set prompt='На стыках подразделений определены правила взаимодействия и передачи результата, поэтому задачи и ответственность не «зависают» между функциями.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='responsibility_determined' and t.locale='ru';
  update public.question_translations t set prompt='Роли, полномочия и ответственность руководителей и подразделений формализованы в необходимой для бизнеса степени, актуальны и реально используются в работе.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='no_conflicts_responsibility' and t.locale='ru';
  update public.question_translations t set prompt='Для основных типов управленческих решений понятно, на каком уровне они должны приниматься и кто обладает необходимыми полномочиями для окончательного решения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='interaction_departments' and t.locale='ru';
  update public.question_translations t set prompt='Как правило, вопросы не поднимаются на более высокий уровень без необходимости: решения принимаются максимально близко к месту возникновения задачи при наличии необходимых полномочий и компетенций.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='structure_relevant_strategy' and t.locale='ru';
  update public.question_translations t set prompt='Организационная структура периодически пересматривается с учётом стратегии, роста компании и фактических проблем управления, а результаты внесённых изменений оцениваются после внедрения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='responsibility_for_decisions' and t.locale='ru';
  update public.question_translations t set prompt='Ключевые сквозные процессы компании определены от входа или потребности клиента до конечного результата и понятны основным участникам процесса.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='process_description' and t.locale='ru';
  update public.question_translations t set prompt='У каждого критически важного процесса есть персональный владелец, отвечающий за его конечный результат и развитие процесса в целом.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='process_responsibility' and t.locale='ru';
  update public.question_translations t set prompt='Для повторяющихся критически важных операций существуют необходимые стандарты и регламенты; они актуальны, доступны сотрудникам и реально применяются.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='process_executors_trained' and t.locale='ru';
  update public.question_translations t set prompt='По ключевым процессам определены показатели результата и эффективности, позволяющие оценивать качество, сроки, стоимость, производительность, потери и другие существенные параметры.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='rules_interaction_departments' and t.locale='ru';
  update public.question_translations t set prompt='Компания понимает финансовую и операционную эффективность на необходимом для управления уровне — по направлениям, продуктам, клиентским сегментам, заказам или процессам, там, где это существенно для принятия решений.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='rules_and_standards_established' and t.locale='ru';
  update public.question_translations t set prompt='Существенные отклонения и сбои анализируются с выявлением корневых причин, после чего принимаются и контролируются корректирующие меры.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='process_indicators_measured' and t.locale='ru';
  update public.question_translations t set prompt='Руководители и сотрудники владеют понятными методами анализа процессов, выявления потерь и причин неэффективности и регулярно используют их для совершенствования работы.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='process_bottlenecks_known' and t.locale='ru';
  update public.question_translations t set prompt='Улучшение процессов ведётся системно, а результаты изменений оцениваются по фактическому изменению сроков, качества, затрат, производительности или клиентского результата.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='system_analysis_bottlenecks' and t.locale='ru';
  update public.question_translations t set prompt='Основные операционные результаты достаточно стабильны и предсказуемы, чтобы компания могла планировать объёмы, сроки, качество и ресурсы без постоянного режима аврала.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='continuous_improvement_cycle' and t.locale='ru';
  update public.question_translations t set prompt='Автоматизация эффективно применяется в ключевых процессах и позволяет существенно снизить ручной труд, количество ошибок, время выполнения операций или зависимость от отдельных сотрудников.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_improve_processes' and t.locale='ru';
  update public.question_translations t set prompt='У компании есть ограниченное число чётко сформулированных приоритетных целей на год, которые понятны руководителям и служат основой для распределения внимания и ресурсов.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='goals_and_metrics_for_year' and t.locale='ru';
  update public.question_translations t set prompt='Для каждой существенной цели определены конкретный измеримый результат, срок достижения и персональный владелец результата.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='all_goals_are_interconnected' and t.locale='ru';
  update public.question_translations t set prompt='Цели компании последовательно декомпозированы до целей подразделений и ключевых руководителей так, чтобы было понятно, какой вклад обеспечивает каждый уровень управления.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_understand_goals' and t.locale='ru';
  update public.question_translations t set prompt='У каждого руководителя и ключевого сотрудника есть ограниченное число приоритетных результатов, и он понимает, как их достижение связано с общими целями компании.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='all_goals_are_measurable' and t.locale='ru';
  update public.question_translations t set prompt='Компания использует систему целей и показателей как полноценный управленческий цикл: планирует результаты, измеряет факт, выявляет отклонения, анализирует их причины и принимает корректирующие решения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='indicators_related_responsible' and t.locale='ru';
  update public.question_translations t set prompt='Система показателей сбалансирована: она отражает не только финансовые результаты, но и состояние клиентов, процессов, качества, команды и других факторов, оказывающих влияние на результат.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='there_are_early_warning_indicators' and t.locale='ru';
  update public.question_translations t set prompt='Руководители регулярно сопоставляют плановые и фактические показатели, анализируют причины существенных отклонений и используют результаты анализа при принятии решений.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='performance_data_trusted' and t.locale='ru';
  update public.question_translations t set prompt='Цели и показатели пересматриваются, когда существенно меняются стратегия, рыночные условия или исходные предположения, а не сохраняются формально до конца планового периода.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='indicators_are_not_contradictory' and t.locale='ru';
  update public.question_translations t set prompt='Система вознаграждения поддерживает достижение значимых результатов и необходимое компании поведение и не создаёт стимулов улучшать отдельный показатель в ущерб общему результату.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='comparison_of_plan_and_actual' and t.locale='ru';
  update public.question_translations t set prompt='По ключевым показателям существуют единые правила расчёта и понятные источники данных; информация обновляется с необходимой периодичностью и воспринимается руководителями как достоверная основа для принятия решений.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='decisions_on_indicators_deviations' and t.locale='ru';
  update public.question_translations t set prompt='В компании существует согласованный календарь регулярных управленческих встреч и обзоров, соответствующий различным горизонтам управления — оперативному, тактическому и стратегическому.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='planning_and_control_cycle' and t.locale='ru';
  update public.question_translations t set prompt='У каждого регулярного управленческого формата есть конкретная цель, круг участников, необходимые входные данные, регламент и понятный ожидаемый результат.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='discussion_of_plan_implementation' and t.locale='ru';
  update public.question_translations t set prompt='Участники приходят на управленческие встречи подготовленными, а необходимые данные доступны заранее и не становятся предметом длительного выяснения непосредственно на совещании.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='causes_of_deviations_are_identified' and t.locale='ru';
  update public.question_translations t set prompt='Управленческие встречи сосредоточены прежде всего на существенных отклонениях, причинах, вариантах действий и решениях, а не на простом обмене информацией.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='decisions_have_deadlines_persons' and t.locale='ru';
  update public.question_translations t set prompt='По итогам встреч фиксируются решения, ответственные и сроки, а выполнение принятых решений систематически контролируется.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='decisions_systematically_monitored' and t.locale='ru';
  update public.question_translations t set prompt='В компании есть единое доступное место, где можно увидеть действующие управленческие решения, ответственных, сроки исполнения и текущий статус каждого решения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='escalation_of_complex_problems' and t.locale='ru';
  update public.question_translations t set prompt='Операционные, тактические и стратегические вопросы рассматриваются в соответствующих управленческих контурах и не смешиваются без необходимости.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='plans_are_being_promptly_adjusted' and t.locale='ru';
  update public.question_translations t set prompt='Регулярные обзоры результатов приводят к конкретным корректирующим действиям, изменению приоритетов или перераспределению ресурсов, когда это необходимо.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='crossfunction_issues_resolved_jointly' and t.locale='ru';
  update public.question_translations t set prompt='Для существенных проблем существует понятный механизм эскалации: вопрос быстро попадает на тот уровень управления, где есть необходимые полномочия для его решения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='management_cycles_are_regulated' and t.locale='ru';
  update public.question_translations t set prompt='Межфункциональные вопросы регулярно рассматриваются совместно заинтересованными подразделениями, а проблемы на стыках доводятся до конкретных решений и контроля исполнения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='no_need_for_manual_control' and t.locale='ru';
  update public.question_translations t set prompt='Состав топ-команды соответствует текущей стратегии и задачам компании; мы понимаем, каких управленческих и профессиональных компетенций команде не хватает.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='competence_management_team' and t.locale='ru';
  update public.question_translations t set prompt='У каждого члена топ-команды есть чётко определённая зона результата, необходимые полномочия и персональная ответственность за принимаемые решения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_are_independent' and t.locale='ru';
  update public.question_translations t set prompt='Члены топ-команды принимают большинство решений в пределах своих полномочий самостоятельно, не перекладывая ответственность на генерального директора или собственника.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='honest_discussions_within_team' and t.locale='ru';
  update public.question_translations t set prompt='В топ-команде можно открыто поднимать проблемы, риски, сомнения и плохие новости, в том числе когда эта информация неприятна другим членам команды или руководителю.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_implement_decisions' and t.locale='ru';
  update public.question_translations t set prompt='Команда умеет конструктивно обсуждать разногласия, рассматривать различные точки зрения и принимать решения, не переводя содержательный конфликт в личный.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='the_leaders_act_as_one_team' and t.locale='ru';
  update public.question_translations t set prompt='Принятые договорённости выполняются; если выполнить их невозможно, об этом сообщают заранее и инициируют пересмотр решения, а не констатируют срыв постфактум.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='first_person_delegates_authority' and t.locale='ru';
  update public.question_translations t set prompt='Работа членов топ-команды регулярно оценивается по результатам и управленческому поведению, а выводы используются для развития, изменения роли, ротации или других кадровых решений.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_do_development_tasks' and t.locale='ru';
  update public.question_translations t set prompt='Развитие руководителей носит системный характер: необходимые компетенции определяются, целенаправленно развиваются и оцениваются по изменению результатов и управленческой практики.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_are_constantly_learning' and t.locale='ru';
  update public.question_translations t set prompt='Члены топ-команды принимают решения в интересах компании в целом, а не оптимизируют только результаты собственной функции или подразделения.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='company_forming_personnel_reserve' and t.locale='ru';
  update public.question_translations t set prompt='Для критически важных руководящих ролей компания понимает риски зависимости от конкретных людей, имеет потенциальных преемников или план замещения и системно готовит сотрудников к более высокой ответственности.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='the_team_can_act_independently' and t.locale='ru';
  update public.question_translations t set prompt='У компании есть ясные приоритеты развития продуктов, услуг и клиентской ценности, связанные со стратегией и изменениями потребностей рынка.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='personal_responsibility_of_managers' and t.locale='ru';
  update public.question_translations t set prompt='Существует управляемый процесс создания и развития новых продуктов, услуг или бизнес-моделей — от выявления потребности и проверки гипотезы до запуска и оценки результата.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='personal_results_and_indicators' and t.locale='ru';
  update public.question_translations t set prompt='У компании есть понятные критерии выбора инициатив развития: мы сравниваем их стратегическую ценность, ожидаемый эффект, риски и необходимые ресурсы и умеем не только запускать, но и своевременно останавливать проекты.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='authority_and_responsibility_balance' and t.locale='ru';
  update public.question_translations t set prompt='Мы понимаем, как должна изменяться сама организация по мере роста и развития бизнеса, и имеем представление о необходимом развитии структуры, процессов, технологий и компетенций на ближайшие 2–3 года.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='rewards_encourage_goal_achievement' and t.locale='ru';
  update public.question_translations t set prompt='Значимые организационные изменения управляются как полноценные проекты или программы с определёнными целями, владельцами, ресурсами, сроками и критериями результата.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='managers_are_rewarded_for_results' and t.locale='ru';
  update public.question_translations t set prompt='В компании действует постоянный механизм генерации, отбора, проверки и масштабирования новых идей, а инновации не зависят исключительно от эпизодической инициативы отдельных сотрудников.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_receive_recognition_results' and t.locale='ru';
  update public.question_translations t set prompt='Компания системно выделяет необходимые ресурсы — людей, время и деньги — на исследования, эксперименты, разработку новых решений и проверку перспективных гипотез.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='failure_to_comply_has_consequences' and t.locale='ru';
  update public.question_translations t set prompt='В компании можно безопасно проводить обоснованные контролируемые эксперименты; неудачная гипотеза рассматривается как источник знания, если эксперимент был корректно проведён и его выводы использованы.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_receive_feedback' and t.locale='ru';
  update public.question_translations t set prompt='Технологические, рыночные и другие существенные тренды регулярно оцениваются с точки зрения их возможного влияния на бизнес, а перспективные возможности переводятся в конкретные инициативы развития.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='responsibility_is_personalized' and t.locale='ru';
  update public.question_translations t set prompt='Инновационная деятельность создаёт измеримый эффект: новые или существенно улучшенные продукты, процессы, технологии или бизнес-модели дают подтверждённую ценность клиентам и компании.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='its_not_customary_shift_responsibility' and t.locale='ru';
  update public.question_translations t set prompt='У нас есть чётко определённые ценности, известные каждому члену коллектива, и это не просто слова — они реально влияют на поведение людей.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='leaders_exemplify_values' and t.locale='ru';
  update public.question_translations t set prompt='Руководители всех уровней своим фактическим поведением демонстрируют те нормы и принципы, которых компания ожидает от сотрудников.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='talk_openly_about_problems' and t.locale='ru';
  update public.question_translations t set prompt='Компания понимает, какая культура необходима для реализации её стратегии, и целенаправленно развивает соответствующие нормы поведения и взаимодействия.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='errors_require_identifying_causes' and t.locale='ru';
  update public.question_translations t set prompt='Сотрудники и руководители могут открыто сообщать о проблемах, рисках и ошибках, в том числе когда эта информация неприятна вышестоящему руководству.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_show_initiative' and t.locale='ru';
  update public.question_translations t set prompt='Базовые правила взаимодействия, ответственности и допустимого поведения применяются последовательно независимо от должности, статуса и личной близости сотрудника к руководству.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='cross_functional_cooperation' and t.locale='ru';
  update public.question_translations t set prompt='При ошибках и сбоях компания стремится выявить причины и улучшить систему, одновременно сохраняя персональную ответственность за сознательное нарушение правил и договорённостей.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employee_participation_in_management' and t.locale='ru';
  update public.question_translations t set prompt='Корпоративная культура помогает компании привлекать и удерживать сильных сотрудников, создавая условия для профессионального развития, реализации способностей и продуктивного сотрудничества.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='fulfillment_of_obligations_is_valued' and t.locale='ru';
  update public.question_translations t set prompt='Сотрудники не только получают информацию о целях, планах и изменениях компании, но имеют работающие каналы обратной связи, обсуждения проблем и внесения предложений.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='respond_quickly_to_changes' and t.locale='ru';
  update public.question_translations t set prompt='Сотрудничество между подразделениями строится вокруг результата компании и клиента, а функциональные границы не становятся препятствием для решения общих задач.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_receive_full_information' and t.locale='ru';
  update public.question_translations t set prompt='Сотрудники имеют достаточную самостоятельность в своей зоне ответственности, а обоснованные инициативы и предложения по улучшению получают поддержку и возможность реализации.' from public.questions q where t.question_id=q.id and q.version_id=v_version and q.key='employees_are_committed_to_values' and t.locale='ru';
  insert into public.question_options (id,question_id,key,position,score_value)
  select gen_random_uuid(),q2.new_id,o.key,o.position,o.score_value from _stage12_questions q2 join public.question_options o on o.question_id=q2.old_id;
  insert into public.question_option_translations (option_id,locale,label)
  select o2.id,t.locale,t.label from public.question_options o2 join _stage12_questions q2 on q2.new_id=o2.question_id join public.question_options old_o on old_o.question_id=q2.old_id and old_o.key=o2.key join public.question_option_translations t on t.option_id=old_o.id;
  insert into public.scoring_policies (version_id,engine_key,engine_version,schema_version,configuration,policy_hash)
  select v_version,engine_key,engine_version,schema_version,configuration,'stage12-1-mvp-question-bank-v2' from public.scoring_policies where version_id=v_old_version;
end $$;
commit;
